# Criando a conexão com banco de dados locais
[connections.respostas_checklist_db]
url = "sqlite:///data/respostas_checklist.db"

[connections.itens_checklist_db]
url = "sqlite:///data/itens_checklist.db"

[connections.funcionarios_db]
url = "sqlite:///data/funcionarios_db.db"